---
# tasks file for ansible.archyay
- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ srcdir }}/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "{{ srcdir }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
